// Dhewadha Foundation Data - Replace images with actual photos when available
// NO BACKEND: All data here is static. Wire to CMS or API endpoints as needed.

export const programs = [
    {
        id: 'education',
        slug: 'education',
        title: 'Education for All',
        shortDescription: 'Providing free educational support, books, and learning materials to underprivileged children in Dhewadha and neighboring villages.',
        description: 'We provide quality education and learning resources to children in Dhewadha, Pakri Barawan, Dumrawan, Konandpur, and Madhepur. Our after-school programs ensure quality learning for students who lack access to proper educational facilities. Through comprehensive educational support, we are building an educated society where no child is left behind.',
        icon: '📚',
        image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=1200&q=80&auto=format&fit=crop',
        beneficiaries: '500+',
        activities: [
            'Free educational support and tutoring',
            'Distribution of books and learning materials',
            'After-school programs in rural villages',
            'Digital literacy training for students',
            'Scholarship support for meritorious students',
        ],
        stories: [
            {
                name: 'Priya from Dhewadha',
                quote: 'The free books and after-school tutoring helped me score well in my exams. Now I dream of becoming a teacher and helping other children in my village.',
                image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80&auto=format&fit=crop',
            },
        ],
        faqs: [
            { question: 'Which villages do you serve?', answer: 'We serve Dhewadha, Pakri Barawan, Dumrawan, Madhepur, Konandpur, Poksi, Datraul, Dola, Dosut, Aruri, and Keshauri in Nawada District.' },
            { question: 'How can my child join the program?', answer: 'Visit our center in Dhewadha village or contact us. We welcome all children from underprivileged families in the region.' },
        ],
    },
    {
        id: 'women-empowerment',
        slug: 'women-empowerment',
        title: 'Women Empowerment',
        shortDescription: 'Empowering rural women through skill development and vocational training for financial independence.',
        description: 'Through skill development programs and vocational training, we empower rural women in Nawada District to become financially independent. Our initiatives include tailoring, handicrafts, and entrepreneurship training that enables women to contribute to household income and build sustainable livelihoods.',
        icon: '👩‍🏫',
        image: 'https://images.unsplash.com/photo-1509099836639-18ba9f7b5d3d?w=1200&q=80&auto=format&fit=crop',
        beneficiaries: '200+',
        activities: [
            'Tailoring and handicraft training',
            'Self-help group formation',
            'Entrepreneurship development programs',
            'Microfinance support and guidance',
            'Market linkage for products',
        ],
        stories: [
            {
                name: 'Anjali Devi',
                quote: 'After learning tailoring, I started my own small business. Now I earn enough to support my childrens education and contribute to my family.',
                image: 'https://images.unsplash.com/photo-1520975914731-8aa8f3a7e7d1?w=400&q=80&auto=format&fit=crop',
            },
        ],
        faqs: [
            { question: 'What skills are taught?', answer: 'We offer tailoring, handicrafts, basic entrepreneurship, financial literacy, and small business management training.' },
            { question: 'Is there any training fee?', answer: 'No, our training programs are free for women from economically disadvantaged backgrounds in the region.' },
        ],
    },
    {
        id: 'healthcare',
        slug: 'healthcare',
        title: 'Healthcare & Nutrition',
        shortDescription: 'Organizing health camps, nutrition awareness programs, and providing essential medical support to rural families.',
        description: 'We organize regular health camps, nutrition awareness programs, and provide essential medical support to families in remote villages of Pakri Barawan Block. Our focus is on maternal health, child nutrition, and preventive healthcare to ensure healthy communities in rural Bihar.',
        icon: '🏥',
        image: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=1200&q=80&auto=format&fit=crop',
        beneficiaries: '1,000+',
        activities: [
            'Regular health camps in remote villages',
            'Free medical consultations and check-ups',
            'Nutrition awareness programs',
            'Maternal and child health services',
            'Preventive healthcare education',
        ],
        stories: [
            {
                name: 'Ramesh Kumar',
                quote: 'The free health camp in our village helped detect my mother\'s health issue early. The timely treatment saved her life. We are grateful to Dhewadha Foundation.',
                image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&q=80&auto=format&fit=crop',
            },
        ],
        faqs: [
            { question: 'How often are health camps conducted?', answer: 'We organize health camps regularly in different villages across Pakri Barawan Block. Check our Events page for schedules.' },
            { question: 'Are services completely free?', answer: 'Yes, all basic consultations, check-ups, and medicines provided at our camps are completely free of cost.' },
        ],
    },
    {
        id: 'livelihood',
        slug: 'livelihood',
        title: 'Livelihood & Skill Development',
        shortDescription: 'Creating sustainable livelihood opportunities through agricultural training, animal husbandry, and small business development.',
        description: 'We create sustainable livelihood opportunities through agricultural training, animal husbandry programs, and small business development initiatives tailored for rural communities. Our programs help families in Nawada District achieve economic stability and self-reliance.',
        icon: '💼',
        image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1200&q=80&auto=format&fit=crop',
        beneficiaries: '300+',
        activities: [
            'Agricultural training and support',
            'Animal husbandry programs',
            'Small business development initiatives',
            'Vocational skills training',
            'Market linkage support',
        ],
        stories: [
            {
                name: 'Suresh from Pakri Barawan',
                quote: 'The agricultural training helped me improve my farming methods. My crop yield has increased, and my family\'s income has grown significantly.',
                image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&q=80&auto=format&fit=crop',
            },
        ],
        faqs: [
            { question: 'Who can participate in these programs?', answer: 'Any individual or family from rural communities in Nawada District seeking to improve their livelihood can join our programs.' },
            { question: 'Do you provide ongoing support?', answer: 'Yes, we provide continuous mentorship and support even after the training to ensure sustainable outcomes.' },
        ],
    },
];

export const gallery = [
    {
        id: 1,
        url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=1200&q=80&auto=format&fit=crop',
        alt: 'Children studying in classroom',
        caption: 'Students at our education center in Dhewadha village',
        program: 'education',
    },
    {
        id: 2,
        url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80&auto=format&fit=crop',
        alt: 'Rural Bihar village scene',
        caption: 'Community outreach in Pakri Barawan villages',
        program: 'all',
    },
    {
        id: 3,
        url: 'https://images.unsplash.com/photo-1509099836639-18ba9f7b5d3d?w=1200&q=80&auto=format&fit=crop',
        alt: 'Women learning vocational skills',
        caption: 'Women empowerment training in Nawada District',
        program: 'women-empowerment',
    },
    {
        id: 4,
        url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&q=80&auto=format&fit=crop',
        alt: 'Students with books',
        caption: 'Free book distribution to children in rural schools',
        program: 'education',
    },
    {
        id: 5,
        url: 'https://images.unsplash.com/photo-1520975914731-8aa8f3a7e7d1?w=1200&q=80&auto=format&fit=crop',
        alt: 'Woman working on sewing machine',
        caption: 'Tailoring training program for rural women',
        program: 'women-empowerment',
    },
    {
        id: 6,
        url: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=1200&q=80&auto=format&fit=crop',
        alt: 'Health camp in village',
        caption: 'Free health camp serving families in Pakri Barawan',
        program: 'healthcare',
    },
    {
        id: 7,
        url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=1200&q=80&auto=format&fit=crop',
        alt: 'Children in after-school program',
        caption: 'After-school tutoring program in Dhewadha',
        program: 'education',
    },
    {
        id: 8,
        url: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=1200&q=80&auto=format&fit=crop',
        alt: 'Volunteers working',
        caption: 'Our volunteers distributing educational materials',
        program: 'all',
    },
    {
        id: 9,
        url: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1200&q=80&auto=format&fit=crop',
        alt: 'Agricultural training',
        caption: 'Agricultural training for sustainable livelihood',
        program: 'livelihood',
    },
    {
        id: 10,
        url: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=1200&q=80&auto=format&fit=crop',
        alt: 'Women in community meeting',
        caption: 'Self-help group meeting in rural Bihar',
        program: 'women-empowerment',
    },
    {
        id: 11,
        url: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1200&q=80&auto=format&fit=crop',
        alt: 'Rural farming scene',
        caption: 'Livelihood programs supporting local farmers',
        program: 'livelihood',
    },
    {
        id: 12,
        url: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=1200&q=80&auto=format&fit=crop',
        alt: 'Community celebration',
        caption: 'Community celebration in Dhewadha village',
        program: 'all',
    },
];

export const events = [
    {
        id: 1,
        slug: 'health-camp-pakri-barawan-2025',
        title: 'Health Camp - Pakri Barawan Block',
        date: '2025-11-20',
        location: 'Dhewadha Village, Pakri Barawan, Nawada',
        type: 'upcoming',
        shortDescription: 'Free health camp providing medical consultations, check-ups, and medicines to 200+ families.',
        fullDescription: 'Join us for a comprehensive health camp in Dhewadha village. We will provide free medical consultations, basic diagnostics, medicines, and health awareness sessions. Focus areas include maternal health, child nutrition, and preventive care for rural families.',
        image: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=1200&q=80&auto=format&fit=crop',
        registrationRequired: false,
    },
    {
        id: 2,
        slug: 'education-material-distribution-2025',
        title: 'Educational Material Distribution Drive',
        date: '2025-12-01',
        location: 'Multiple villages - Pakri Barawan Block',
        type: 'upcoming',
        shortDescription: 'Distributing free books, notebooks, and learning materials to 500+ children across 15 villages.',
        fullDescription: 'Our annual education material distribution drive will reach children across Dhewadha, Pakri Barawan, Dumrawan, Madhepur, Konandpur, and other villages. Each child will receive books, notebooks, stationery, and learning materials to support their education.',
        image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=1200&q=80&auto=format&fit=crop',
        registrationRequired: false,
    },
    {
        id: 3,
        slug: 'women-skill-training-workshop',
        title: 'Women Skill Development Workshop',
        date: '2025-10-15',
        location: 'Dhewadha Village, Nawada',
        type: 'past',
        shortDescription: 'Two-week intensive tailoring and handicraft training for 50 rural women.',
        fullDescription: 'Successfully completed a comprehensive skill development workshop for rural women. Participants learned tailoring, handicrafts, and basic entrepreneurship skills. All graduates received certificates and support for starting their own small businesses.',
        image: 'https://images.unsplash.com/photo-1509099836639-18ba9f7b5d3d?w=1200&q=80&auto=format&fit=crop',
        registrationRequired: false,
    },
    {
        id: 4,
        slug: 'community-awareness-program-2025',
        title: 'Community Health & Hygiene Awareness Program',
        date: '2025-09-25',
        location: 'Pakri Barawan Villages',
        type: 'past',
        shortDescription: 'Conducted awareness sessions on health, hygiene, and nutrition in 10 villages.',
        fullDescription: 'Our volunteers conducted comprehensive awareness sessions across multiple villages in Pakri Barawan Block, reaching over 300 families. Topics covered included hygiene practices, nutrition for children, and preventive healthcare measures.',
        image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=1200&q=80&auto=format&fit=crop',
        registrationRequired: false,
    },
];

export const blogPosts = [
    {
        id: 1,
        slug: 'transforming-rural-bihar-education',
        title: 'Transforming Rural Bihar Through Education',
        excerpt: 'How grassroots educational initiatives in Dhewadha and surrounding villages are breaking the cycle of poverty and building a prosperous society.',
        content: 'Education is the cornerstone of development, especially in rural areas of Bihar where access to quality learning remains a challenge. In Dhewadha village and surrounding areas of Pakri Barawan Block, many children lack basic educational resources...',
        author: 'Rishav Mishra',
        date: '2025-10-01',
        readTime: '6 min read',
        image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=1200&q=80&auto=format&fit=crop',
        category: 'Education',
    },
    {
        id: 2,
        slug: 'women-empowerment-nawada-district',
        title: 'Empowering Women in Nawada District',
        excerpt: 'Stories of transformation as rural women gain financial independence through skill development and vocational training.',
        content: 'In the rural villages of Pakri Barawan Block, women have traditionally been limited in their economic opportunities. Through our women empowerment programs, we are witnessing remarkable transformations...',
        author: 'Rishav Mishra',
        date: '2025-09-20',
        readTime: '5 min read',
        image: 'https://images.unsplash.com/photo-1520975914731-8aa8f3a7e7d1?w=1200&q=80&auto=format&fit=crop',
        category: 'Women Empowerment',
    },
    {
        id: 3,
        slug: 'healthcare-challenges-rural-bihar',
        title: 'Addressing Healthcare Challenges in Rural Bihar',
        excerpt: 'The critical importance of mobile health camps and preventive care in underserved villages of Nawada District.',
        content: 'Healthcare accessibility remains a significant challenge in rural Bihar. Villages in Pakri Barawan Block often lack proper medical facilities, forcing families to travel long distances for basic healthcare...',
        author: 'Team Dhewadha Foundation',
        date: '2025-09-05',
        readTime: '7 min read',
        image: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=1200&q=80&auto=format&fit=crop',
        category: 'Healthcare',
    },
    {
        id: 4,
        slug: 'volunteer-stories-dhewadha',
        title: 'Volunteer Stories: Making a Difference in Dhewadha',
        excerpt: 'Inspiring stories from volunteers working to transform rural communities in Pakri Barawan Block.',
        content: 'Our volunteers are the backbone of Dhewadha Foundation. Their dedication and commitment to serving rural communities has created lasting impact...',
        author: 'Team Dhewadha Foundation',
        date: '2025-08-28',
        readTime: '4 min read',
        image: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=1200&q=80&auto=format&fit=crop',
        category: 'Stories',
    },
    {
        id: 5,
        slug: 'sustainable-livelihoods-rural-families',
        title: 'Building Sustainable Livelihoods for Rural Families',
        excerpt: 'How agricultural training and skill development programs are creating economic opportunities in Nawada District.',
        content: 'Economic empowerment is key to breaking the cycle of poverty. In Dhewadha and surrounding villages, we are working with families to create sustainable livelihood opportunities...',
        author: 'Rishav Mishra',
        date: '2025-08-15',
        readTime: '6 min read',
        image: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1200&q=80&auto=format&fit=crop',
        category: 'Livelihood',
    },
    {
        id: 6,
        slug: 'community-development-pakri-barawan',
        title: 'Holistic Community Development in Pakri Barawan',
        excerpt: 'A comprehensive approach to rural development addressing education, health, and economic empowerment simultaneously.',
        content: 'True development requires a holistic approach. In Pakri Barawan Block, our integrated programs address multiple aspects of community development simultaneously...',
        author: 'Rishav Mishra',
        date: '2025-08-01',
        readTime: '8 min read',
        image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80&auto=format&fit=crop',
        category: 'Impact',
    },
];

export const team = [
    {
        id: 1,
        name: 'Rishav Mishra',
        role: 'Founder & Director',
        bio: 'Rishav Mishra founded Dhewadha Foundation with a vision to transform his native village and surrounding communities. Born and raised in Dhewadha, he witnessed firsthand the challenges faced by rural families and is committed to creating lasting positive change in Nawada District.',
        image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80&auto=format&fit=crop',
    },
    {
        id: 2,
        name: 'Program Coordinator - Education',
        role: 'Education Program Lead',
        bio: 'Leading our educational initiatives across 15+ villages in Pakri Barawan Block, ensuring every child has access to quality learning resources and support.',
        image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&q=80&auto=format&fit=crop',
    },
    {
        id: 3,
        name: 'Women Empowerment Coordinator',
        role: 'Women Programs Lead',
        bio: 'Managing skill development and vocational training programs for rural women, helping them achieve financial independence and empowerment.',
        image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80&auto=format&fit=crop',
    },
    {
        id: 4,
        name: 'Healthcare Coordinator',
        role: 'Health Programs Lead',
        bio: 'Organizing health camps and medical support services across remote villages in Nawada District, focusing on preventive care and maternal health.',
        image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80&auto=format&fit=crop',
    },
    {
        id: 5,
        name: 'Volunteer Coordinator',
        role: 'Volunteer Management',
        bio: 'Managing our network of 100+ volunteers who dedicate their time to serve rural communities across Pakri Barawan Block.',
        image: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&q=80&auto=format&fit=crop',
    },
    {
        id: 6,
        name: 'Operations Manager',
        role: 'Operations & Logistics',
        bio: 'Overseeing operational efficiency and ensuring smooth execution of programs across multiple villages in Nawada District.',
        image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=80&auto=format&fit=crop',
    },
];

export const partners = [
    { name: 'Bihar Rural Development', logo: 'BRD' },
    { name: 'Nawada District Administration', logo: 'NDA' },
    { name: 'Local NGO Partners', logo: 'LNP' },
    { name: 'Community Organizations', logo: 'CO' },
    { name: 'Educational Institutions', logo: 'EI' },
    { name: 'Healthcare Providers', logo: 'HP' },
];

export const stats = [
    { label: 'Children Impacted', value: 500, suffix: '+' },
    { label: 'Women Empowered', value: 200, suffix: '+' },
    { label: 'Villages Served', value: 15, suffix: '+' },
    { label: 'Active Volunteers', value: 100, suffix: '+' },
];

// Contact Information
export const contactInfo = {
    address: {
        village: 'Dhewadha',
        block: 'Pakri Barawan (Pakribarawan)',
        postOffice: 'Pakaribarwan',
        district: 'Nawada',
        state: 'Bihar',
        pinCode: '805124',
        country: 'India',
    },
    location: {
        distanceFromNawada: '24 KM',
        distanceFromBlock: '4 KM',
        distanceFromPatna: '108 KM',
        elevation: '63 meters',
        division: 'Magadh Division',
    },
    villagesServed: [
        'Dhewadha (Dhewadha Chhatarwar)',
        'Pakri Barawan',
        'Dumrawan',
        'Madhepur',
        'Konandpur',
        'Poksi',
        'Datraul',
        'Dola',
        'Dosut',
        'Aruri',
        'Keshauri',
    ],
};
